
- name: Install pip3
  when: "virtual_mode"
  package:
    name: python3-pip
    state: latest
    
- name: Install yq
  when: "virtual_mode"
  snap:
    name: yq
    state: present

- name: Install pip dependencies
  pip:
    requirements: "{{ playbook_dir }}/services/requirements.txt"
    executable: pip3
    
- name: get the username running the deploy
  become: no
  local_action: command whoami
  register: username_on_the_host

- name: Copy Django secret key file
  copy:
    src: config/django_secret_key.txt
    dest: "{{ installation_path }}/.django_secret_key.txt"
    owner: "{{ username_on_the_host.stdout_lines[0] }}"
    mode: "0600"

- name: Check for redis installation
  stat:
    path: "{{ installation_path }}/redis/src/redis-server"
  register: stat_output

- name: Create redis directory
  become: no
  file:
    path: "{{ installation_path }}/redis"
    state: directory

- name: Download redis 
  become: no
  unarchive:
    src: http://download.redis.io/releases/redis-7.0.5.tar.gz
    dest: "{{ installation_path }}/redis"
    remote_src: yes
    extra_opts: [--strip-components=1]
  when: not stat_output.stat.exists

- name: Install redis
  become: no
  make:
    chdir: "{{ installation_path }}/redis"
  when: not stat_output.stat.exists
